"""Classless CSS framework registry."""

from __future__ import annotations

# (key, display_name, head_html) — alphabetical by display name
# head_html is the full <link> snippet(s) to inject into <head>.
CSS_FRAMEWORKS: list[tuple[str, str, str]] = [
    ("almond", "Almond.CSS",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/alvaromontoro/almond.css@latest/dist/almond.min.css" />'),
    ("attricss", "attriCSS",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/raj457036/attriCSS@master/attri.css" />'),
    ("awsm", "awsm.css",
     '<link rel="stylesheet" href="https://unpkg.com/awsm.css/dist/awsm.min.css" />'),
    ("axist", "axist",
     '<link rel="stylesheet" href="https://unpkg.com/axist@latest/dist/axist.min.css" />'),
    ("bahunya", "Bahunya",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/kimeiga/bahunya/dist/bahunya.min.css" />'),
    ("bamboo", "Bamboo CSS",
     '<link rel="stylesheet" href="https://unpkg.com/bamboo.css/dist/light.min.css" />'),
    ("bare", "BareCSS",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/barecss@latest/css/bare.min.css" />'),
    ("basic", "Basic.css",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vladocar/Basic.css@master/css/basic.css" />'),
    ("bolt", "Bolt.css",
     '<link rel="stylesheet" href="https://unpkg.com/boltcss/bolt.min.css" />'),
    ("chimera", "ChimeraCSS",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/chimeracss@latest/dist/chimera.min.css" />'),
    ("classless", "Classless.css",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/digitallytailored/classless@latest/classless.min.css" />'),
    ("concrete", "concrete.css",
     '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/concrete.css/3.1.0/concrete.min.css" />'),
    ("dev", "dev.css",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@intergrav/dev.css@4" />'),
    ("downstyler", "Downstyler",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/waldyrious/downstyler@latest/dist/downstyler.css" />'),
    ("fylgja", "Fylgja",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fylgja/base@latest/base.css" />'),
    ("holiday", "holiday.css",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/holiday.css@0.11.5" />'),
    ("latex", "LaTeX.css",
     '<link rel="stylesheet" href="https://unpkg.com/latex.css/style.min.css" />'),
    ("magick", "magick.css",
     '<link rel="stylesheet" href="https://unpkg.com/normalize.css" />\n<link rel="stylesheet" href="https://unpkg.com/magick.css" />'),
    ("matcha", "Matcha CSS",
     '<link rel="stylesheet" href="https://matcha.mizu.sh/matcha.css" />'),
    ("md-air", "Markdown CSS — Air",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/nicebyte/markdowncss@latest/air.css" />'),
    ("md-modest", "Markdown CSS — Modest",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/nicebyte/markdowncss@latest/modest.css" />'),
    ("md-retro", "Markdown CSS — Retro",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/nicebyte/markdowncss@latest/retro.css" />'),
    ("md-splendor", "Markdown CSS — Splendor",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/nicebyte/markdowncss@latest/splendor.css" />'),
    ("marx", "Marx",
     '<link rel="stylesheet" href="https://unpkg.com/marx-css/css/marx.min.css" />'),
    ("mercury", "MercuryCSS",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/wmeredith/MercuryCSS@latest/css/mercury.min.css" />'),
    ("mvp", "MVP.css",
     '<link rel="stylesheet" href="https://unpkg.com/mvp.css" />'),
    ("new", "new.css",
     '<link rel="stylesheet" href="https://fonts.xz.style/serve/inter.css" />\n<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@exampledev/new.css@1/new.min.css" />'),
    ("no-class", "no-class.css",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/davidpaulsson/no-class.css@latest/no-class.css" />'),
    ("pico", "Pico.css",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.classless.min.css" />\n<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.colors.min.css" />'),
    ("ridge", "ridge.css",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/nicholasgasior/ridge.css@latest/ridge.min.css" />'),
    ("sakura", "sakura",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sakura.css/css/sakura.css" />'),
    ("shadcn", "shadcn-classless",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fordus/shadcn-classless@main/dist/shadcn-classless.css" />'),
    ("simple", "Simple.css",
     '<link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css" />'),
    ("spcss", "SPCSS",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/spcss@0.9.0" />'),
    ("style", "style.css",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/css-pkg/style.css@latest/style.css" />'),
    ("stylize", "Stylize.css",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vasanthv/stylize.css@latest/stylize.css" />'),
    ("tacit", "tacit",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tacit-css@1.9.5/dist/tacit-css.min.css" />'),
    ("tiny", "Tiny.css",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vhf/tiny.css@latest/tiny.css" />'),
    ("tty", "tty.css",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/nicebyte/tty.css@latest/tty.css" />'),
    ("tufte", "Tufte CSS",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tufte-css@1.8.0/tufte.min.css" />'),
    # µCSS themes: Azure (default), Red, Pumpkin, Orange, Amber, Yellow, Lime,
    # Green, Jade, Cyan, Blue, Indigo, Violet, Purple, Fuchsia, Pink, Sand,
    # Grey, Zinc, Slate
    ("µcss", "µCSS",
     """
      <!-- Azure (default), Red, Pumpkin, Orange, Amber, Yellow, Lime,  Green, Jade, Cyan, Blue, Indigo, Violet, Purple, Fuchsia, Pink, Sand,  Grey, Zinc, Slate -->
      <link rel=\"stylesheet\" href=\"https://unpkg.com/@digicreon/mucss/dist/mu.fuchsia.css\" />"""),
    ("w3c", "W3C Core Styles",
     '<link rel="stylesheet" href="https://www.w3.org/StyleSheets/Core/Chocolate" type="text/css" />'),
    ("water", "water.css",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.min.css" />'),
    ("writ", "Writ",
     '<link rel="stylesheet" href="https://writ.cmcenroe.me/1.0.4/writ.min.css" />'),
    ("yorha", "YoRHa",
     '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/yorha@latest/dist/yorha.min.css" />'),
]
